In [1]:
import pandas as pd 
import numpy as np 
import os
from pathlib import Path

### Data Paths

In [2]:
os.chdir(Path().resolve())

In [3]:
 # Use raw string (r"") for Windows paths
print(os.getcwd())  # Verify the change

c:\Users\Amanda\Documents\Capstone\DSE6311OM_Group3\Notebook

In [4]:
grads = "../Data/gradrates.xlsx"
acctblty = "../Data/Accountability.xlsx"
percapita = "../Data/DOR_Income_EQV_Per_Capita.xlsx"
perpupil = "../Data/PerPupilExpenditures.xlsx" 
population = "../Data/selectedpopulations.xlsx" 
teacher = "../Data/teacherdata.xlsx" 
charterschools = "../Data/schooldistricts_charter.csv"
townschools="../Data/schooldistricts_Town.csv"

### Datasets
Convert Excel data sets to pandas dataframes to merge into one dataframe. - E.T.

In [5]:
df_grads = pd.read_excel(grads, header = 1)
df_acctblty = pd.read_excel(acctblty, header = 1)
df_percapita = pd.read_excel(percapita, header = 0)
df_perpupil = pd.read_excel(perpupil, header = 1)
df_population = pd.read_excel(population, header = 1)
df_teacher = pd.read_excel(teacher, header = 1)
df_charterschool = pd.read_csv(charterschools,header=0)
df_townschool = pd.read_csv(townschools,header=0)

In [6]:
df_grads

,District Name,District Code,# in Cohort,% Graduated,% Still in School,% Non-Grad Completers,% H.S. Equiv.,% Dropped Out,% Permanently Excluded
0,Abby Kelley Foster Charter Public (District),4450000,88,100.0,0.0,0.0,0.0,0.0,0.0
1,Abington,10000,153,88.9,1.3,0.7,0.0,9.2,0.0
2,Academy Of the Pacific Rim Charter Public (Dis...,4120000,54,96.3,1.9,0.0,0.0,1.9,0.0
3,Acton-Boxborough,6000000,466,96.1,3.2,0.2,0.0,0.4,0.0
4,Advanced Math and Science Academy Charter (Dis...,4300000,139,99.3,0.7,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
301,Winchester,3440000,354,94.1,3.4,0.3,0.3,2.0,0.0
302,Winthrop,3460000,136,92.6,1.5,0.0,0.0,5.9,0.0
303,Woburn,3470000,291,89.7,4.1,0.3,0.0,5.8,0.0
304,Worcester,3480000,"1,862",85.2,6.1,1.1,0.1,7.4,0.0
305,State Totals,0,"72,602",89.2,4.5,0.9,0.2,5.3,0.0

In [7]:
df_acctblty

,District Name,District Code,Overall Classification,Reason for Classification,Progress Toward Improvement Targets (%)
0,Abby Kelley Foster Charter Public (District),4450000,Not requiring assistance or intervention,Meeting or exceeding targets,82.0
1,Abington,10000,Not requiring assistance or intervention,Moderate progress toward targets,39.0
2,Academy Of the Pacific Rim Charter Public (Dis...,4120000,Not requiring assistance or intervention,Moderate progress toward targets,48.0
3,Acton-Boxborough,6000000,Not requiring assistance or intervention,Meeting or exceeding targets,85.0
4,Acushnet,30000,Not requiring assistance or intervention,Substantial progress toward targets,58.0
...,...,...,...,...,...
393,Winthrop,3460000,Not requiring assistance or intervention,Substantial progress toward targets,56.0
394,Woburn,3470000,Not requiring assistance or intervention,Moderate progress toward targets,32.0
395,Worcester,3480000,Not requiring assistance or intervention,Moderate progress toward targets,41.0
396,Worthington,3490000,Not requiring assistance or intervention,Limited or no progress toward targets,9.0
397,Wrentham,3500000,Not requiring assistance or intervention,Substantial progress toward targets,63.0

In [8]:
df_percapita

,DOR Code,LEA Code,Municipality,County,Cherry Sheet FY,Population,DOR Income,DOR Income Per Capita,EQV,EQV Per Capita
0,1,1,Abington,PLYMOUTH,2023,17062,645765000,37848,2379458500,139460
1,2,2,Acton,MIDDLESEX,2023,24021,1733168000,72152,4940912200,205691
2,3,3,Acushnet,BRISTOL,2023,10559,376411000,35648,1346443900,127516
3,4,4,Adams,BERKSHIRE,2023,8166,191139000,23407,549332800,67271
4,5,5,Agawam,HAMPDEN,2023,28692,893064000,31126,3286756800,114553
...,...,...,...,...,...,...,...,...,...,...
346,347,347,Woburn,MIDDLESEX,2023,40876,1829233000,44751,9226467200,225718
347,348,348,Worcester,WORCESTER,2023,206518,4638107000,22459,15426121200,74696
348,349,349,Worthington,HAMPSHIRE,2023,1193,34443000,28871,182949300,153352
349,350,350,Wrentham,NORFOLK,2023,12178,738007000,60602,2481220700,203746
350,351,351,Yarmouth,BARNSTABLE,2023,25023,876692000,35035,6880187700,274955

In [9]:
df_perpupil

,District Name,District Code,In-District Expenditures,Total In-district FTEs,In-District Expenditures per Pupil,Total Expenditures,Total Pupil FTEs,Total Expenditures per Pupil
0,Abby Kelley Foster Charter Public (District),4450000,"$24,231,438.78","1,415.8","$17,114.65","$24,231,438.78","1,415.8","$17,114.65"
1,Abington,10000,"$35,603,421.16","2,143.5","$16,609.95","$41,098,932.87","2,297.3","$17,890.10"
2,Academy Of the Pacific Rim Charter Public (Dis...,4120000,"$12,801,946.92",467.4,"$27,392.63","$12,801,946.92",467.4,"$27,392.63"
3,Acton-Boxborough,6000000,"$100,564,755.40","5,181.7","$19,407.68","$109,746,603.20","5,302.1","$20,698.70"
4,Acushnet,30000,"$14,679,700.00",965.8,"$15,199.52","$18,752,410.80","1,254.7","$14,945.73"
...,...,...,...,...,...,...,...,...
393,Woburn,3470000,"$94,093,579.73","4,289.4","$21,936.30","$105,328,116.50","4,516.7","$23,319.71"
394,Worcester,3480000,"$501,140,676.40","24,319.6","$20,606.45","$568,546,854.00","27,234.8","$20,875.75"
395,Worthington,3490000,"$1,904,264.00",75.5,"$25,222.04","$2,822,565.38",142.1,"$19,863.23"
396,Wrentham,3500000,"$17,626,509.66",920.9,"$19,140.53","$19,059,388.49",981.1,"$19,426.55"
397,State Totals,0,"$18,401,964,825.00","865,749.1","$21,255.54","$20,737,958,663.00","947,578.4","$21,885.22"

In [10]:
df_population

,District Name,District Code,High Needs#,High Needs%,English Learners#,English Learners%,First Language Not English#,First Language Not English%,Low Income#,Low Income%,Students with Disabilities#,Students with Disabilities%,Students with Disabilities#.1,Students with Disabilities%.1
0,Abby Kelley Foster Charter Public (District),4450000,"1,005",70.7,256,18.0,967,68.0,837,58.9,,,166,11.7
1,Abington,10000,"1,029",47.3,236,11.0,362,16.9,736,34.4,,,387,17.8
2,Academy Of the Pacific Rim Charter Public (Dis...,4120000,332,71.1,44,9.4,158,33.8,273,58.5,,,115,24.6
3,Acton-Boxborough,6000000,"1,538",29.6,317,6.2,"1,141",22.2,546,10.6,,,803,15.5
4,Acushnet,30000,415,42.7,6,0.6,17,1.8,320,33.2,,,154,15.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,Woburn,3470000,"2,332",53.6,461,10.8,894,20.9,"1,653",38.7,,,896,20.6
395,Worcester,3480000,"20,471",82.9,"7,386",30.4,"14,201",58.4,"17,636",72.5,,,"5,250",21.2
396,Worthington,3490000,41,53.9,0,0.0,0,0.0,30,39.5,,,17,22.4
397,Wrentham,3500000,284,29.8,24,2.5,51,5.4,135,14.2,,,167,17.5
398,State Totals,0,"508,820",55.1,"110,554",12.1,"228,169",25.0,"386,060",42.3,,,"179,095",19.4

In [11]:
df_teacher

,District Name,District Code,Total # of Teachers (FTE),% of Teachers Licensed,Student / Teacher Ratio,Percent of Experienced Teachers,Percent of Teachers without Waiver or Provisional License,Percent Teaching In-Field
0,Abby Kelley Foster Charter Public (District),4450000,119.6,99.2,11.9 to 1,81.5,88.3,90.5
1,Abington,10000,153.8,97.1,13.9 to 1,81.3,89.6,95.7
2,Academy Of the Pacific Rim Charter Public (Dis...,4120000,49.6,65.6,9.4 to 1,37.3,95.6,47.3
3,Acton-Boxborough,6000000,395.4,100.0,13.0 to 1,88.3,97.5,98.8
4,Acushnet,30000,76.0,100.0,12.7 to 1,78.9,92.1,94.7
...,...,...,...,...,...,...,...,...
394,Woburn,3470000,374.6,99.2,11.4 to 1,85.7,96.1,95.7
395,Worcester,3480000,"1,715.9",97.6,14.2 to 1,77.3,89.8,93.0
396,Worthington,3490000,9.2,100.0,8.3 to 1,69.6,87.0,100.0
397,Wrentham,3500000,79.4,100.0,12.0 to 1,85.3,100.0,100.0
398,State Totals,0,"76,977.6",97.1,11.9 to 1,81.3,93.4,92.3

In [12]:
df_population.isnull().sum() 

## the original dataset doesn't have the columns "Students with Disabilities# , Students with Disabilities% " 
## For this reason I checked why there is no data in these columns. It doesn't say null but it doesn't have any info either. 
## After I combined the datasets, I dropped these columns. - E.T.

District Name                    0
District Code                    0
High Needs#                      0
High Needs%                      0
English Learners#                0
English Learners%                0
First Language Not English#      0
First Language Not English%      0
Low Income#                      0
Low Income%                      0
Students with Disabilities#      0
Students with Disabilities%      0
Students with Disabilities#.1    0
Students with Disabilities%.1    0
dtype: int64

### Merge Datasets (LEFT join)

* I applied LEFT Join
* Keep the df_population datasets as left table since it has the highest number of rows(399)
* Then merged each datasets and dropped the "District Name" other wise it was creating duplicates - E.T.

In [13]:
# Start with base DataFrame
df = df_population.copy()

# Merge and drop redundant 'District Name' after each merge
df = df.merge(df_acctblty.drop(columns=['District Name']), on='District Code', how='left')
df = df.merge(df_perpupil.drop(columns=['District Name']), on='District Code', how='left')
df = df.merge(df_grads.drop(columns=['District Name']), on='District Code', how='left')
df = df.merge(df_teacher.drop(columns=['District Name']), on='District Code', how='left')

In [14]:
df.shape

(399, 36)

In [15]:
df.columns

Index(['District Name', 'District Code', 'High Needs#', 'High Needs%',
       'English Learners#', 'English Learners%', 'First Language Not English#',
       'First Language Not English%', 'Low Income#', 'Low Income%',
       'Students with Disabilities#', 'Students with Disabilities%',
       'Students with Disabilities#.1', 'Students with Disabilities%.1',
       'Overall Classification', 'Reason for Classification',
       'Progress Toward Improvement Targets (%)', 'In-District Expenditures',
       'Total In-district FTEs', 'In-District Expenditures per Pupil',
       'Total Expenditures', 'Total Pupil FTEs',
       'Total Expenditures per Pupil', '# in Cohort', '% Graduated',
       '% Still in School', '% Non-Grad Completers', '% H.S. Equiv.',
       '% Dropped Out', '% Permanently Excluded', 'Total # of Teachers (FTE)',
       '% of Teachers Licensed', 'Student / Teacher Ratio',
       'Percent of Experienced Teachers',
       'Percent of Teachers without Waiver or Provisional License',
       'Percent Teaching In-Field'],
      dtype='object')

In [16]:
df.isnull().sum()

District Name                                                 0
District Code                                                 0
High Needs#                                                   0
High Needs%                                                   0
English Learners#                                             0
English Learners%                                             0
First Language Not English#                                   0
First Language Not English%                                   0
Low Income#                                                   0
Low Income%                                                   0
Students with Disabilities#                                   0
Students with Disabilities%                                   0
Students with Disabilities#.1                                 0
Students with Disabilities%.1                                 0
Overall Classification                                        1
Reason for Classification                                     1
Progress Toward Improvement Targets (%)                      10
In-District Expenditures                                      2
Total In-district FTEs                                        1
In-District Expenditures per Pupil                            1
Total Expenditures                                            2
Total Pupil FTEs                                              1
Total Expenditures per Pupil                                  1
# in Cohort                                                  93
% Graduated                                                  93
% Still in School                                            93
% Non-Grad Completers                                        93
% H.S. Equiv.                                                93
% Dropped Out                                                93
% Permanently Excluded                                       93
Total # of Teachers (FTE)                                     2
% of Teachers Licensed                                        2
Student / Teacher Ratio                                       1
Percent of Experienced Teachers                               3
Percent of Teachers without Waiver or Provisional License     3
Percent Teaching In-Field                                     4
dtype: int64

In [17]:
df.dtypes

District Name                                                 object
District Code                                                  int64
High Needs#                                                   object
High Needs%                                                  float64
English Learners#                                             object
English Learners%                                            float64
First Language Not English#                                   object
First Language Not English%                                  float64
Low Income#                                                   object
Low Income%                                                  float64
Students with Disabilities#                                   object
Students with Disabilities%                                   object
Students with Disabilities#.1                                 object
Students with Disabilities%.1                                float64
Overall Classification                                        object
Reason for Classification                                     object
Progress Toward Improvement Targets (%)                      float64
In-District Expenditures                                      object
Total In-district FTEs                                        object
In-District Expenditures per Pupil                            object
Total Expenditures                                            object
Total Pupil FTEs                                              object
Total Expenditures per Pupil                                  object
# in Cohort                                                   object
% Graduated                                                  float64
% Still in School                                            float64
% Non-Grad Completers                                        float64
% H.S. Equiv.                                                float64
% Dropped Out                                                float64
% Permanently Excluded                                       float64
Total # of Teachers (FTE)                                     object
% of Teachers Licensed                                       float64
Student / Teacher Ratio                                       object
Percent of Experienced Teachers                              float64
Percent of Teachers without Waiver or Provisional License    float64
Percent Teaching In-Field                                    float64
dtype: object

### Combine DESE data with DOR data. - F.R.

In [18]:
df.head()
df_charterschool.head()
is_charter = df['District Name'].str.contains('charter', case=False, na=False)
df.loc[is_charter, 'CleanedName'] = df.loc[is_charter, 'District Name'].str.replace(r"\s*\(District\)", "", regex=True).str.strip().str.lower()

df_charterschool['CleanedName'] = (
    df_charterschool['NAME']
    .str.lower()
    .str.replace(r"school", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)  
    .str.strip()
)


df = df.merge(
    df_charterschool[['CleanedName', 'MEMBERS']],
    how='left',
    left_on='CleanedName',
    right_on='CleanedName'
)


df_townschool['DISTRICT_N'] = df_townschool['DISTRICT_N'].str.strip()
#left join 
df = df.merge(
    df_townschool[['DISTRICT_N', 'MEMBERLIST']].rename(columns={'MEMBERLIST': 'MEMBERS_townschool'}),
    how='left',
    left_on='District Name',
    right_on='DISTRICT_N',
    suffixes=('', '_townschool')
)


# This step will populate if the school district has more than 1 towns
df['MEMBERS'] = df['MEMBERS'].fillna(df['MEMBERS_townschool'])
# This step is to populate when there is only member town and the member list is empty in schooltown ds
df['MEMBERS'] = df['MEMBERS'].fillna(df['District Name'])
df.drop(columns='DISTRICT_N', inplace=True)
df.drop(columns='MEMBERS_townschool', inplace=True)
df.head()

,District Name,District Code,High Needs#,High Needs%,English Learners#,English Learners%,First Language Not English#,First Language Not English%,Low Income#,Low Income%,...,% Dropped Out,% Permanently Excluded,Total # of Teachers (FTE),% of Teachers Licensed,Student / Teacher Ratio,Percent of Experienced Teachers,Percent of Teachers without Waiver or Provisional License,Percent Teaching In-Field,CleanedName,MEMBERS
0,Abby Kelley Foster Charter Public (District),4450000,"1,005",70.7,256,18.0,967,68.0,837,58.9,...,0.0,0.0,119.6,99.2,11.9 to 1,81.5,88.3,90.5,abby kelley foster charter public,"Auburn, Leicester, Millbury, Oxford, Shrewsbur..."
1,Abington,10000,"1,029",47.3,236,11.0,362,16.9,736,34.4,...,9.2,0.0,153.8,97.1,13.9 to 1,81.3,89.6,95.7,NaN,Abington
2,Academy Of the Pacific Rim Charter Public (Dis...,4120000,332,71.1,44,9.4,158,33.8,273,58.5,...,1.9,0.0,49.6,65.6,9.4 to 1,37.3,95.6,47.3,academy of the pacific rim charter public,Boston
3,Acton-Boxborough,6000000,"1,538",29.6,317,6.2,"1,141",22.2,546,10.6,...,0.4,0.0,395.4,100.0,13.0 to 1,88.3,97.5,98.8,NaN,"Acton, Boxborough"
4,Acushnet,30000,415,42.7,6,0.6,17,1.8,320,33.2,...,NaN,NaN,76.0,100.0,12.7 to 1,78.9,92.1,94.7,NaN,Acushnet

In [19]:
def get_avg_stats(members_str, df_percapita):
    
    towns = [t.strip() for t in members_str.split(',')] if pd.notnull(members_str) else []

    matched = df_percapita[df_percapita['Municipality'].isin(towns)]
 
    if not matched.empty:
        return pd.Series({
            'Population': matched['Population'].sum(),
            'DOR Income Per Capita': matched['DOR Income Per Capita'].mean()
        })
    else:
        return pd.Series({'Population': None, 'DOR Income Per Capita': None})


df[['Population', 'DOR Income Per Capita']] = df['MEMBERS'].apply(get_avg_stats, df_percapita=df_percapita)
df.head()

,District Name,District Code,High Needs#,High Needs%,English Learners#,English Learners%,First Language Not English#,First Language Not English%,Low Income#,Low Income%,...,Total # of Teachers (FTE),% of Teachers Licensed,Student / Teacher Ratio,Percent of Experienced Teachers,Percent of Teachers without Waiver or Provisional License,Percent Teaching In-Field,CleanedName,MEMBERS,Population,DOR Income Per Capita
0,Abby Kelley Foster Charter Public (District),4450000,"1,005",70.7,256,18.0,967,68.0,837,58.9,...,119.6,99.2,11.9 to 1,81.5,88.3,90.5,abby kelley foster charter public,"Auburn, Leicester, Millbury, Oxford, Shrewsbur...",317231.0,40029.375
1,Abington,10000,"1,029",47.3,236,11.0,362,16.9,736,34.4,...,153.8,97.1,13.9 to 1,81.3,89.6,95.7,NaN,Abington,17062.0,37848.000
2,Academy Of the Pacific Rim Charter Public (Dis...,4120000,332,71.1,44,9.4,158,33.8,273,58.5,...,49.6,65.6,9.4 to 1,37.3,95.6,47.3,academy of the pacific rim charter public,Boston,675647.0,55038.000
3,Acton-Boxborough,6000000,"1,538",29.6,317,6.2,"1,141",22.2,546,10.6,...,395.4,100.0,13.0 to 1,88.3,97.5,98.8,NaN,"Acton, Boxborough",29527.0,69189.500
4,Acushnet,30000,415,42.7,6,0.6,17,1.8,320,33.2,...,76.0,100.0,12.7 to 1,78.9,92.1,94.7,NaN,Acushnet,10559.0,35648.000

### Drop columsn that are not needed for analysis - these columns represent the count of students percentage of students will be used for these features as it is more useful for comparative analysis make these changes in df (inplace = True) - A.F.

In [20]:

df.drop([
    'High Needs#', 
    'English Learners#', 
    'First Language Not English#', 
    'Low Income#', 'Students with Disabilities#.1', 
    'CleanedName', 
    '# in Cohort', 
    'District Code'], 
    axis = 1, inplace=True)

# expand the display options for better visibility of the dataframe - A.F.
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 300)

# check changes made to the dataframe - A.F.
df.head()
df.shape

(399, 32)

### Drop rows where graduation rate = NaN; these districts do not include high school grades and feed into other districts for grades 9-12 
### 93 rows will be dropped - A.F.

In [21]:
df.dropna(subset = ["% Graduated"], inplace = True)
df.shape

(306, 32)

### Check column names in the dataframe to see where changes are needed 
### Rename columns to be more readable and consistent with Python naming conventions- E.T.

In [22]:
df.columns

Index(['District Name', 'High Needs%', 'English Learners%',
       'First Language Not English%', 'Low Income%',
       'Students with Disabilities#', 'Students with Disabilities%',
       'Students with Disabilities%.1', 'Overall Classification',
       'Reason for Classification', 'Progress Toward Improvement Targets (%)',
       'In-District Expenditures', 'Total In-district FTEs',
       'In-District Expenditures per Pupil', 'Total Expenditures',
       'Total Pupil FTEs', 'Total Expenditures per Pupil', '% Graduated',
       '% Still in School', '% Non-Grad Completers', '% H.S. Equiv.',
       '% Dropped Out', '% Permanently Excluded', 'Total # of Teachers (FTE)',
       '% of Teachers Licensed', 'Student / Teacher Ratio',
       'Percent of Experienced Teachers',
       'Percent of Teachers without Waiver or Provisional License',
       'Percent Teaching In-Field', 'MEMBERS', 'Population',
       'DOR Income Per Capita'],
      dtype='object')

In [23]:
df.rename(columns={
    'District Name': 'district_name',
    'High Needs%' : 'high_needs_pct',
    'English Learners%' : 'english_learners_pct',
    'First Language Not English%' : 'first_language_not_english_pct',
    'Low Income%': 'low_income_pct',
    'Students with Disabilities%.1': 'students_with_disabilities_pct',
    'Overall Classification': 'overall_classification',
    'Reason for Classification': 'reason_for_classification',
    'Progress Toward Improvement Targets (%)': 'progress_toward_improvement_targets_pct',
    'In-District Expenditures': 'in_district_expenditures',
    'Total In-district FTEs': 'total_in_district_FTEs',
    'In-District Expenditures per Pupil': 'in_district_expenditures_per_pupil',
    'Total Expenditures': 'total_expenditures',
    'Total Pupil FTEs': 'total_pupil_FTEs',
    'Total Expenditures per Pupil': 'total_expenditures_per_pupil',
    '% Graduated': 'graduation_rate_pct',
    '% Still in School': 'still_in_school_pct',
    '% Non-Grad Completers': 'non_grad_completers_pct',
    '% H.S. Equiv.': 'hs_equivalency_pct',
    '% Dropped Out': 'dropout_rate_pct',
    '% Permanently Excluded': 'permanently_excluded_pct',
    'Total # of Teachers (FTE)': 'total_teachers_FTE',
    '% of Teachers Licensed': 'teachers_licensed_pct',
    'Student / Teacher Ratio': 'student_teacher_ratio',
    'Percent of Experienced Teachers': 'experienced_teachers_pct',
    'Percent of Teachers without Waiver or Provisional License': 'teachers_without_waiver_pct',
    'Percent Teaching In-Field': 'teaching_in_field_pct',
    'MEMBERS': 'members', 
    'Population': 'population', 
    'DOR Income Per Capita' : 'DOR_income_per_capita'}, inplace=True)

In [24]:
# check the changes made to the dataframe
df.head()

,district_name,high_needs_pct,english_learners_pct,first_language_not_english_pct,low_income_pct,Students with Disabilities#,Students with Disabilities%,students_with_disabilities_pct,overall_classification,reason_for_classification,progress_toward_improvement_targets_pct,in_district_expenditures,total_in_district_FTEs,in_district_expenditures_per_pupil,total_expenditures,total_pupil_FTEs,total_expenditures_per_pupil,graduation_rate_pct,still_in_school_pct,non_grad_completers_pct,hs_equivalency_pct,dropout_rate_pct,permanently_excluded_pct,total_teachers_FTE,teachers_licensed_pct,student_teacher_ratio,experienced_teachers_pct,teachers_without_waiver_pct,teaching_in_field_pct,members,population,DOR_income_per_capita
0,Abby Kelley Foster Charter Public (District),70.7,18.0,68.0,58.9,,,11.7,Not requiring assistance or intervention,Meeting or exceeding targets,82.0,"$24,231,438.78","1,415.8","$17,114.65","$24,231,438.78","1,415.8","$17,114.65",100.0,0.0,0.0,0.0,0.0,0.0,119.6,99.2,11.9 to 1,81.5,88.3,90.5,"Auburn, Leicester, Millbury, Oxford, Shrewsbur...",317231.0,40029.375
1,Abington,47.3,11.0,16.9,34.4,,,17.8,Not requiring assistance or intervention,Moderate progress toward targets,39.0,"$35,603,421.16","2,143.5","$16,609.95","$41,098,932.87","2,297.3","$17,890.10",88.9,1.3,0.7,0.0,9.2,0.0,153.8,97.1,13.9 to 1,81.3,89.6,95.7,Abington,17062.0,37848.000
2,Academy Of the Pacific Rim Charter Public (Dis...,71.1,9.4,33.8,58.5,,,24.6,Not requiring assistance or intervention,Moderate progress toward targets,48.0,"$12,801,946.92",467.4,"$27,392.63","$12,801,946.92",467.4,"$27,392.63",96.3,1.9,0.0,0.0,1.9,0.0,49.6,65.6,9.4 to 1,37.3,95.6,47.3,Boston,675647.0,55038.000
3,Acton-Boxborough,29.6,6.2,22.2,10.6,,,15.5,Not requiring assistance or intervention,Meeting or exceeding targets,85.0,"$100,564,755.40","5,181.7","$19,407.68","$109,746,603.20","5,302.1","$20,698.70",96.1,3.2,0.2,0.0,0.4,0.0,395.4,100.0,13.0 to 1,88.3,97.5,98.8,"Acton, Boxborough",29527.0,69189.500
5,Advanced Math and Science Academy Charter (Dis...,26.0,1.4,23.6,16.0,,,6.8,Not requiring assistance or intervention,Meeting or exceeding targets,82.0,"$15,065,009.41",964.3,"$15,623.23","$15,065,009.41",964.3,"$15,623.23",99.3,0.7,0.0,0.0,0.0,0.0,80.5,92.3,12.0 to 1,80.8,78.9,82.8,"Clinton, Hudson, Marlborough, Maynard",88059.0,37880.000

### Change the Student / teacher ratio values to the numeric by keeping the first decimal value as data. - E.T.

In [25]:
df["student_teacher_ratio"] = (
    df["student_teacher_ratio"]
    .astype(str)
    .str.extract(r'([\d\.]+)')  # Extract numeric part before 'to'
    .astype(float)
)

In [26]:
df.head()

,district_name,high_needs_pct,english_learners_pct,first_language_not_english_pct,low_income_pct,Students with Disabilities#,Students with Disabilities%,students_with_disabilities_pct,overall_classification,reason_for_classification,progress_toward_improvement_targets_pct,in_district_expenditures,total_in_district_FTEs,in_district_expenditures_per_pupil,total_expenditures,total_pupil_FTEs,total_expenditures_per_pupil,graduation_rate_pct,still_in_school_pct,non_grad_completers_pct,hs_equivalency_pct,dropout_rate_pct,permanently_excluded_pct,total_teachers_FTE,teachers_licensed_pct,student_teacher_ratio,experienced_teachers_pct,teachers_without_waiver_pct,teaching_in_field_pct,members,population,DOR_income_per_capita
0,Abby Kelley Foster Charter Public (District),70.7,18.0,68.0,58.9,,,11.7,Not requiring assistance or intervention,Meeting or exceeding targets,82.0,"$24,231,438.78","1,415.8","$17,114.65","$24,231,438.78","1,415.8","$17,114.65",100.0,0.0,0.0,0.0,0.0,0.0,119.6,99.2,11.9,81.5,88.3,90.5,"Auburn, Leicester, Millbury, Oxford, Shrewsbur...",317231.0,40029.375
1,Abington,47.3,11.0,16.9,34.4,,,17.8,Not requiring assistance or intervention,Moderate progress toward targets,39.0,"$35,603,421.16","2,143.5","$16,609.95","$41,098,932.87","2,297.3","$17,890.10",88.9,1.3,0.7,0.0,9.2,0.0,153.8,97.1,13.9,81.3,89.6,95.7,Abington,17062.0,37848.000
2,Academy Of the Pacific Rim Charter Public (Dis...,71.1,9.4,33.8,58.5,,,24.6,Not requiring assistance or intervention,Moderate progress toward targets,48.0,"$12,801,946.92",467.4,"$27,392.63","$12,801,946.92",467.4,"$27,392.63",96.3,1.9,0.0,0.0,1.9,0.0,49.6,65.6,9.4,37.3,95.6,47.3,Boston,675647.0,55038.000
3,Acton-Boxborough,29.6,6.2,22.2,10.6,,,15.5,Not requiring assistance or intervention,Meeting or exceeding targets,85.0,"$100,564,755.40","5,181.7","$19,407.68","$109,746,603.20","5,302.1","$20,698.70",96.1,3.2,0.2,0.0,0.4,0.0,395.4,100.0,13.0,88.3,97.5,98.8,"Acton, Boxborough",29527.0,69189.500
5,Advanced Math and Science Academy Charter (Dis...,26.0,1.4,23.6,16.0,,,6.8,Not requiring assistance or intervention,Meeting or exceeding targets,82.0,"$15,065,009.41",964.3,"$15,623.23","$15,065,009.41",964.3,"$15,623.23",99.3,0.7,0.0,0.0,0.0,0.0,80.5,92.3,12.0,80.8,78.9,82.8,"Clinton, Hudson, Marlborough, Maynard",88059.0,37880.000

### Fill in null values under 'population' column for regional school districts.  Data for these missing values are in the "Missing Regional Schools" table, which is merged with the main dataframe on a left join. - A.F.

In [34]:
updates = "../Data/Missing Regional Schools.xlsx"
df_updates = pd.read_excel(updates, header = 0)
df_updates

,District Name,members,population,DOR_income_per_capita
0,Ayer Shirley School District,"Ayer, Shirley",15910,33866.00000
1,Dudley-Charlton Reg,"Dudley, Charlton",41484,35222.00000
2,Hoosac Valley Regional,"Adams, Cheshire",11424,27161.00000
3,Manchester Essex Regional,"Manchester, Essex",9070,125051.50000
4,Martha's Vineyard,"Aquinnah, Chilmark, Edgartown, Oak Bluffs, Tis...",20530,47239.66667
5,Monomoy Regional School District,"Chatham, Harwich",20034,55943.00000
6,Quaboag Regional,"Warren, West Brookfield",8808,28922.50000
7,Somerset Berkley Regional School District,"Somerset, Berkley",25067,37727.50000

In [35]:
df_updates = df_updates.rename(columns={"District Name": "district_name"})
df_merged = df.merge(df_updates, on="district_name", how="left", suffixes=("", "_update"))

In [36]:
df_merged["population"] = df_merged["population"].fillna(df_merged["population_update"])
df_merged["DOR_income_per_capita"] = df_merged["DOR_income_per_capita"].fillna(df_merged["DOR_income_per_capita_update"])
df_merged["members"]=df_merged["members"].fillna(df_merged["members_update"])

In [37]:
df_merged.head(20)

,district_name,high_needs_pct,english_learners_pct,first_language_not_english_pct,low_income_pct,Students with Disabilities#,Students with Disabilities%,students_with_disabilities_pct,overall_classification,reason_for_classification,progress_toward_improvement_targets_pct,in_district_expenditures,total_in_district_FTEs,in_district_expenditures_per_pupil,total_expenditures,total_pupil_FTEs,total_expenditures_per_pupil,graduation_rate_pct,still_in_school_pct,non_grad_completers_pct,hs_equivalency_pct,dropout_rate_pct,permanently_excluded_pct,total_teachers_FTE,teachers_licensed_pct,student_teacher_ratio,experienced_teachers_pct,teachers_without_waiver_pct,teaching_in_field_pct,members,population,DOR_income_per_capita,members_update,population_update,DOR_income_per_capita_update
0,Abby Kelley Foster Charter Public (District),70.7,18.0,68.0,58.9,,,11.7,Not requiring assistance or intervention,Meeting or exceeding targets,82.0,"$24,231,438.78","1,415.8","$17,114.65","$24,231,438.78","1,415.8","$17,114.65",100.0,0.0,0.0,0.0,0.0,0.0,119.6,99.2,11.9,81.5,88.3,90.5,"Auburn, Leicester, Millbury, Oxford, Shrewsbur...",317231.0,40029.375,NaN,NaN,NaN
1,Abington,47.3,11.0,16.9,34.4,,,17.8,Not requiring assistance or intervention,Moderate progress toward targets,39.0,"$35,603,421.16","2,143.5","$16,609.95","$41,098,932.87","2,297.3","$17,890.10",88.9,1.3,0.7,0.0,9.2,0.0,153.8,97.1,13.9,81.3,89.6,95.7,Abington,17062.0,37848.000,NaN,NaN,NaN
2,Academy Of the Pacific Rim Charter Public (Dis...,71.1,9.4,33.8,58.5,,,24.6,Not requiring assistance or intervention,Moderate progress toward targets,48.0,"$12,801,946.92",467.4,"$27,392.63","$12,801,946.92",467.4,"$27,392.63",96.3,1.9,0.0,0.0,1.9,0.0,49.6,65.6,9.4,37.3,95.6,47.3,Boston,675647.0,55038.000,NaN,NaN,NaN
3,Acton-Boxborough,29.6,6.2,22.2,10.6,,,15.5,Not requiring assistance or intervention,Meeting or exceeding targets,85.0,"$100,564,755.40","5,181.7","$19,407.68","$109,746,603.20","5,302.1","$20,698.70",96.1,3.2,0.2,0.0,0.4,0.0,395.4,100.0,13.0,88.3,97.5,98.8,"Acton, Boxborough",29527.0,69189.500,NaN,NaN,NaN
4,Advanced Math and Science Academy Charter (Dis...,26.0,1.4,23.6,16.0,,,6.8,Not requiring assistance or intervention,Meeting or exceeding targets,82.0,"$15,065,009.41",964.3,"$15,623.23","$15,065,009.41",964.3,"$15,623.23",99.3,0.7,0.0,0.0,0.0,0.0,80.5,92.3,12.0,80.8,78.9,82.8,"Clinton, Hudson, Marlborough, Maynard",88059.0,37880.000,NaN,NaN,NaN
5,Agawam,51.4,6.2,15.4,40.7,,,18.3,Not requiring assistance or intervention,Moderate progress toward targets,46.0,"$71,958,484.59","3,524.8","$20,414.91","$78,821,069.71","3,700.6","$21,299.54",88.0,1.1,1.9,0.4,8.6,0.0,275.6,100.0,12.5,89.4,96.7,96.3,Agawam,28692.0,31126.000,NaN,NaN,NaN
6,Amesbury,46.4,2.7,4.5,33.8,,,23.7,Not requiring assistance or intervention,Moderate progress toward targets,47.0,"$39,966,168.64","1,789.1","$22,338.70","$45,461,590.81","1,981.4","$22,944.18",88.3,2.5,0.8,0.8,7.5,0.0,168.4,100.0,10.6,89.0,95.3,97.7,Amesbury,17366.0,41139.000,NaN,NaN,NaN
7,Amherst-Pelham,44.0,7.3,19.6,29.8,,,24.2,Requiring assistance or intervention,In need of focused/targeted support,33.0,"$32,489,016.00","1,241.1","$26,177.60","$37,562,376.22","1,390.9","$27,005.81",90.9,4.1,0.9,0.9,3.2,0.0,120.1,91.6,10.2,81.3,94.0,84.1,"Amherst, Pelham, Leverett, Shutesbury",44125.0,34325.000,NaN,NaN,NaN
8,Andover,31.3,3.4,17.4,11.5,,,19.2,Not requiring assistance or intervention,Meeting or exceeding targets,76.0,"$120,895,506.40","5,569.1","$21,708.27","$128,212,610.90","5,663.7","$22,637.61",96.3,2.6,0.5,0.0,0.7,0.0,471.0,99.8,11.7,89.2,97.5,99.0,Andover,36569.0,87282.000,NaN,NaN,NaN
9,Argosy Collegiate Charter School (District),85.0,22.1,26.2,74.1,,,24.2,Not requiring assistance or intervention,Moderate progress toward targets,43.0,"$10,104,246.97",546.6,"$18,485.63","$10,104,246.97",546.6,"$18,485.63",74.5,7.3,0.0,0.0,16.4,1.8,32.6,68.9,16.9,47.6,75.2,53.1,Argosy Collegiate Charter School (District),NaN,NaN,NaN,NaN,NaN
10,Arlington,28.2,5.0,13.4,10.5,,,16.5,Not requiring assistance or intervention,Meeting or exceeding targets,89.0,"$113,165,838.50","6,019.7","$18,799.25","$119,119,025.90","6,117.7","$19,471.21",95.6,3.4,0.0,0.0,1.0,0.0,486.3,99.2,12.3,79.5,94.0,97.4,Arlington,46308.0,65927.000,NaN,NaN,NaN
11,Ashburnham-Westminster,37.2,2.3,5.4,25.6,,,17.0,Not requiring assistance or intervention,Moderate progress toward targets,44.0,"$35,763,196.29","2,252.5","$15,877.11","$38,700,936.81","2,350.7","$16,463.58",96.4,1.2,0.0,0.0,2.4,0.0,163.9,98.8,14.1,91.4,96.5,98.3,"Ashburnham, Westminster",14528.0,38202.000,NaN,NaN,NaN
12,Ashland,40.5,9.8,31.4,23.1,,,19.2,Not requiring assistance or intervention,Meeting or exceeding targets,79.0,"$46,927,293.37","2,889.7","$16,239.50","$51,197,608.86","2,950.1","$17,354.53",96.2,0.5,0.5,0.0,2.7,0.0,217.9,99.5,13.3,86.2,98.2,96.9,Ashland,18832.0,53140.000,NaN,NaN,NaN
13,Assabet Valley Regional Vocational Technical,58.9,5.9,23.9,41.0,,,24.1,Not requiring assistance or intervention,Substantial progress toward targets,64.0,"$29,035,656.09","1,092.2","$26,584.56","$29,178,846.47","1,092.8","$26,700.99",97.0,0.0,0.0,0.0,3.0,0.0,111.2,97.3,10.1,88.3,92.8,93.8,Assabet Valley Regional Vocational Technical,NaN,NaN,NaN,NaN,NaN
14,Athol-Royalston,71.3,2.4,5.8,64.4,,,24.8,Not requiring assistance or intervention,Limited or no progress toward targets,23.0,"$28,132,998.00","1,569.9","$17,920.25","$32,176,065.18","1,842.7","$17,461.37",84.5,9.5,1.2,0.0,4.8,0.0,117.8,99.2,13.3,70.6,95.0,92.9,"Athol, Royalston",13195.0,23992.500,NaN,NaN,NaN
15,Atlantis Charter (District),71.0,17.2,30.5,61.4,,,15.1,Not requiring assistance or intervention,Moderate progress toward targets,31.0,"$20,454,702.00","1,288.4","$15,876.67","$20,454,702.00","1,288.4","$15,876.67",92.7,0.0,0.0,0.0,3.7,3.7,105.8,76.4,12.1,57.4,85.1,63.9,Fall River,94000.0,18669.000,NaN,NaN,NaN
16,Attleboro,51.5,6.6,15.9,40.5,,,18.2,Not requiring assistance or intervention,Moderate progress toward targets,47.0,"$99,575,309.06","5,912.2","$16,842.34","$109,262,216.00","6,313.2","$17,306.95",90.8,4.5,0.0,0.0,4.7,0.0,389.4,99.2,15.2,83.4,95.5,95.0,Attleboro,46461.0,34583.000,NaN,NaN,NaN
17,Auburn,37.3,2.3,11.3,27.9,,,12.2,Not requiring assistance or intervention,Moderate progress toward targets,43.0,"$42,145,085.14","2,554.4","$16,499.02","$43,641,167.09","2,601.7","$16,774.10",97.4,0.5,1.0,0.5,0.5,0.0,187.6,99.5,13.6,88.8,94.1,94.5,Auburn,16889.0,38584.000,NaN,NaN,NaN
18,Avon,62.2,12.9,16.0,44.7,,,21.2,Not requiring assistance or intervention,Moderate progress toward targets,42.0,"$13,866,502.00",727.5,"$19,060.48","$15,048,069.59",767.8,"$19,598.94",95.5,2.3,0.0,0.0,2.3,0.0,74.4,100.0,9.8,77.1,94.6,100.0,Avon,4777.0,36559.000,NaN,NaN,NaN
19,Ayer Shirley School District,45.5,4.3,7.4,32.6,,,19.3,Not requiring assistance or intervention,Moderate progress toward targets,42.0,"$32,042,979.18","1,641.4","$19,521.74","$37,038,728.96","1,885.5","$19,643.98",88.9,7.1,2.0,0.0,2.0,0.0,145.8,99.3,11.2,85.0,95.9,94.7,Ayer Shirley School District,15910.0,33866.000,"Ayer, Shirley",15910.0,33866.0

In [38]:
df_final = df_merged.drop(columns=["population_update", "DOR_income_per_capita_update", "members_update"])
df_final = df_final.set_index("district_name")

In [39]:
df=df_final

### Save the Combined Dataset - A.F.

In [40]:
# save the final dataframe to a new Excel file
output_file = "combined_data.xlsx"
df.to_excel(output_file, index= True)

In [41]:
# print the first few rows of the final dataframe
pd.set_option('display.max_columns', None)
df.head()

,high_needs_pct,english_learners_pct,first_language_not_english_pct,low_income_pct,Students with Disabilities#,Students with Disabilities%,students_with_disabilities_pct,overall_classification,reason_for_classification,progress_toward_improvement_targets_pct,in_district_expenditures,total_in_district_FTEs,in_district_expenditures_per_pupil,total_expenditures,total_pupil_FTEs,total_expenditures_per_pupil,graduation_rate_pct,still_in_school_pct,non_grad_completers_pct,hs_equivalency_pct,dropout_rate_pct,permanently_excluded_pct,total_teachers_FTE,teachers_licensed_pct,student_teacher_ratio,experienced_teachers_pct,teachers_without_waiver_pct,teaching_in_field_pct,members,population,DOR_income_per_capita
district_name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Abby Kelley Foster Charter Public (District),70.7,18.0,68.0,58.9,,,11.7,Not requiring assistance or intervention,Meeting or exceeding targets,82.0,"$24,231,438.78","1,415.8","$17,114.65","$24,231,438.78","1,415.8","$17,114.65",100.0,0.0,0.0,0.0,0.0,0.0,119.6,99.2,11.9,81.5,88.3,90.5,"Auburn, Leicester, Millbury, Oxford, Shrewsbur...",317231.0,40029.375
Abington,47.3,11.0,16.9,34.4,,,17.8,Not requiring assistance or intervention,Moderate progress toward targets,39.0,"$35,603,421.16","2,143.5","$16,609.95","$41,098,932.87","2,297.3","$17,890.10",88.9,1.3,0.7,0.0,9.2,0.0,153.8,97.1,13.9,81.3,89.6,95.7,Abington,17062.0,37848.000
Academy Of the Pacific Rim Charter Public (District),71.1,9.4,33.8,58.5,,,24.6,Not requiring assistance or intervention,Moderate progress toward targets,48.0,"$12,801,946.92",467.4,"$27,392.63","$12,801,946.92",467.4,"$27,392.63",96.3,1.9,0.0,0.0,1.9,0.0,49.6,65.6,9.4,37.3,95.6,47.3,Boston,675647.0,55038.000
Acton-Boxborough,29.6,6.2,22.2,10.6,,,15.5,Not requiring assistance or intervention,Meeting or exceeding targets,85.0,"$100,564,755.40","5,181.7","$19,407.68","$109,746,603.20","5,302.1","$20,698.70",96.1,3.2,0.2,0.0,0.4,0.0,395.4,100.0,13.0,88.3,97.5,98.8,"Acton, Boxborough",29527.0,69189.500
Advanced Math and Science Academy Charter (District),26.0,1.4,23.6,16.0,,,6.8,Not requiring assistance or intervention,Meeting or exceeding targets,82.0,"$15,065,009.41",964.3,"$15,623.23","$15,065,009.41",964.3,"$15,623.23",99.3,0.7,0.0,0.0,0.0,0.0,80.5,92.3,12.0,80.8,78.9,82.8,"Clinton, Hudson, Marlborough, Maynard",88059.0,37880.000